### ISSUE TITLE
As a user, I want to filter library members by membership dates so that I can see who was active in the library in a particular time period.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#192]
# testing notes
## designs
[desktop](https://zpl.io/aR1n8en) / [tablet](https://zpl.io/V1NEdXX) / [mobile](https://zpl.io/2GyD4mj)

to test this, visit the [members search page](https://test-shakespeareandco.cdh.princeton.edu/members/).

- does the "membership date" filter visually match the designs, across all screens? resize your browser window to try it at smaller sizes.
- when the page loads, are the placeholder numbers in the two boxes of the filter populated? (note that one will be 2018; this is because of bad data that hasn't yet been fixed in the database).
- when you type into one of the boxes, you should see the results updated as soon as you type a valid 4-digit year. try typing into one box, waiting, then doing the other.
- if you type something that isn't a 4-digit year, **nothing should happen**.
- if you type a year into the first box that is _later_ than the year in the second box (or vice versa), **nothing should happen** since this is an invalid range.
- if something was typed into one of the boxes and you delete all of it, the form should update again.
- the member results should look correct based on the membership dates you enter. 

# dev notes
## checklist
- [x] write initial markup for filter and add mockup version to form (#310)
- [x] write styles (for all screens) for filter based on mockup (#311)
- [x] add indexing for member active dates
- [x] add membership date range field to form
- [x] filter member list view by membership date
- [x] add reactivity by creating `RxRangeFacet` class (#312)
- [x] calculate and pass placeholder values for max/min account years
- [x] server side logic for invalid form 
## approach
In tandem: write initial markup for filter (@thatbudakguy) and indexing/view logic (@bwhicks ); once initial markup is done handoff for django form field logic (@bwhicks); pass back for reactivity (@thatbudakguy)

**Comment by thatbudakguy** [comment]
bumping to a 5 after talking with @bwhicks about the various frontend/backend pieces for this.

**Comment by rlskoeser** [comment]
Checked with project team: any activity on an account should count for the date range filter, not just active subscription.

**Comment by thatbudakguy** [comment]
bumping to 8 because of related work on #327 and continuing work on this.

**Comment by clmahoney** [comment]
- YES the "membership date" filter visually matches the designs across all screens (desktop, mobile, tablet) 
- YES when the page loads the placeholder numbers in the two boxes of the filter populated
- YES when I type into one of the boxes I see the results updated as soon as you type a valid 4-digit year - this works in either box
- YES if I type in something that isn't a 4-digit year, nothing happens 
- **NO** if I type a year into the first box that is later than the year in the second box (or vice versa), nothing should happen since this is an invalid range --> ex. if I type in 1940-1925, I still get results for 1940 FIRST because it loads automatically 
- YES if something was typed into one of the boxes and I delete all of it, the form updates again
- **NO** the member results do NOT look correct based on the membership dates you enter: on desktop, phone and tablet, when I enter in 1919-1920, I get membership dates that are from 1920-1922, 1920-1923, 1920-1925. I also tried entering in 1919-1923 and I got results for just 1925 (Abbott), 1941 (Abdul)

**Comment by thatbudakguy** [comment]
@clmahoney sorry I wasn't clear - nothing should happen _at the point that the range becomes invalid_. if you put 1940 in one box that's a valid search; as soon as you put 1925 in the _other_ box it becomes invalid. so i think the behavior you're describing is correct - you should still see your results for 1940-nothing because nothing happens after you put in 1925.

re: the second problem I tested with 1919-1923 and didn't see Abbott or Abdul. as @rlskoeser mentioned on #327, any member who had any event anywhere in the range is valid, so e.g. 1920-1925 would be valid for that search since it has some dates in between 1919-1923.

**Comment by clmahoney** [comment]
Thank you @thatbudakguy for clarifying! This all looks good, then!
