### ISSUE TITLE
Template & styles: pagination & sorting

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#211]
### designs
**initial**
[desktop](https://zpl.io/aw4AxQK) / [tablet](https://zpl.io/25JevW0) / [mobile](https://zpl.io/2p4Qp8J)

**stuck to top**
[desktop](https://zpl.io/VQBxlPn) / [tablet](https://zpl.io/bAB0eRn) / [mobile](https://zpl.io/adz95OK)

this should look basically the same on both the books list and members list pages - try both so that you can see the different values that show up for the page labels (alphabetical for members, numeric for books). some notes:

 - the mockups show a "go" button; this will **only be present if javascript is turned off**. if you want to see what that looks like, follow [these instructions for chrome](https://stackoverflow.com/questions/13405383/how-to-disable-javascript-in-chrome-developer-tools). you don't need to click "go" if js is turned on (the default); just choose a new page and you should go there immediately.
- the sizing of the dropdowns will be different from the design. unfortunately we can't auto-scale them based on the text, so we have to set a constant size for them.
- the pagination should "stick" to the top of the screen when you scroll past it. when this happens, it should have the slight shadow that's in the designs. if it unsticks, the shadow should go away.
- make sure the right labels are visible: on desktop, you should see the "DISPLAYING / SORT BY" text next to the dropdowns. on tablet and mobile, the labels should be above them and disappear when the controls are "stuck" to the top.
- check the labels on the "next"/"previous" arrows. they shouldn't show up on mobile, to save space.
- it's important that you can still interact with the main menu and home buttons when the page controls are "stuck" up next to them. make sure you can click the home button and/or open the main menu while the pagination is stuck to the top, on all screen sizes.

# dev notes
#### todo
- [x] move DISPLAYING/SORT BY labels up out of sticky area on mobile/tablet
- [x] fix mobile safari not displaying gradients/fade out effect 😠 
- [x] make fade effect smaller to avoid a weird optical illusion with chrome input outlines

**Comment by thatbudakguy** [comment]
todo:
[ ] move DISPLAYING/SORT BY labels up out of sticky area on mobile/tablet
[ ] fix mobile safari not displaying gradients/fade out effect 😠 
[ ] make fade effect smaller to avoid a weird optical illusion with chrome input outlines

**Comment by wafaisfahany** [comment]
*Using Chrome and Safari on a Mac

- The shadow for the pagination stuck to top (scrolled down) does not appear in mobile-mode but is there in desktop and tablet screens: the shadow falls only under the SORTED BY/DISPLAYING tiles. 

<img width="460" alt="Screenshot 2019-04-22 at 09 15 20" src="https://user-images.githubusercontent.com/47332262/56502108-33bcb300-64df-11e9-89ab-259eada98ada.png">

- I disabled js on my chrome (with Devtools) but was not able to see the "go" button on any screen.

Everything else is good and functional.

**Comment by thatbudakguy** [comment]
@wafaisfahany thanks for pointing these out...I'm realizing there are a bunch of things I should have been clearer about!

the location of the shadow under the pagination is determined at the time the page loads, which shouldn't be an issue _except_ in the case where somebody (like you) is testing by resizing their browser window. this means that when you resize it or go into mobile mode, you have to refresh the page first so that it can "realize" the new size of the window and adjust the shadow location accordingly. give this a try and see if it gets it correct.

for disabling js, you also need to refresh right after checking the box. hopefully the article mentioned this, but if not give that a try and see if it changes things. on chrome, refreshing showed me the "go" button after I turned off js.

last thing - the shadow for the pagination won't show up at all _when js is off_, because js is needed to detect when the pagination gets "stuck" to the top. this is normal. if you turn js back on and refresh, it should work again.

**Comment by wafaisfahany** [comment]
Tested! all good -
