### ISSUE TITLE
Update meta description content for dynamic member and book pages

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#598]
## notes for testing
Put test site urls into the [twitter card validator](https://cards-dev.twitter.com/validator) to see how they will display. The title and text under the title comes from page metadata; not all pages have the secondary text (description).

Please check:
- members search & browse
- individual member pages: biography, membership activity, borrowing activity, card list, individual card 
- book search & browse
- individual book pages: bibliography, circulation activity, card list

## dev
- [x] check members list description is accurate
- [x] add member detail page description: "Shakespeare and Company lending library member [year ranges]"
- [x] add member activity page titles
- [x] add member card page description
- [x] add work detail page description: something like “Borrowed or purchased from the Shakespeare and Company lending library [year ranges or circulation counts]“?
- [x] add work circulation page title
- [x] add work card page title
- [x] check work list description is accurate
- [x] member card page image

**Comment by jkotin** [comment]
For a member with a single date:

<img width="661" alt="Screen Shot 2020-05-12 at 9 05 24 PM" src="https://user-images.githubusercontent.com/12616674/81760501-642e1100-9495-11ea-9637-943ce2915770.png">

**Comment by jkotin** [comment]
Search results on books for "Africa":

<img width="661" alt="Screen Shot 2020-05-12 at 9 12 34 PM" src="https://user-images.githubusercontent.com/12616674/81760544-7f008580-9495-11ea-951a-6ba13913c370.png">

**Comment by jkotin** [comment]
Clicking through from a book search for Portrait to a card:

<img width="661" alt="Screen Shot 2020-05-12 at 9 07 28 PM" src="https://user-images.githubusercontent.com/12616674/81760596-a0fa0800-9495-11ea-8ee6-976ff4342421.png">

**Comment by jkotin** [comment]
@rlskoeser is it a problem that there was no preview image for the lending library card?

**Comment by jkotin** [comment]
I did get a preview for https://test-shakespeareandco.cdh.princeton.edu/members/blaess/cards/601c5558-2dfd-47c4-a72d-50ad697c6a6e/.

<img width="661" alt="Screen Shot 2020-05-12 at 9 22 06 PM" src="https://user-images.githubusercontent.com/12616674/81760982-b6bbfd00-9496-11ea-8e65-ce2df3381902.png">

**Comment by rlskoeser** [comment]
@jkotin I had problems where the twitter card validator wouldn't show the card image on the first try but it would on the second — I'm _hoping_ this is a problem on the twitter card validator side, because I'm pretty sure I am generating the correct image urls for these. I'm using PUL IIIF image urls, so they are a bit different from the other site images.

@jkotin does the title and description text you looked at all look fine? Would you like @clmahoney to review these?

**Comment by jkotin** [comment]
I do think it would be great if @clmahoney would test.  She can close if everything looks good.  I'm not sure if I tried all the different pages.

The titles and descriptions are fine with me. I'm not sure what the options/parameters are. E.g. "Bernice Abbott / Shakespeare and Company lending library member 1926" might be better as "Bernice Abbott / Shakespeare and Company lending library member in 1926." But I see that the preposition would need to change based on the situation. I'm happy to sign off as it stands!

**Comment by rlskoeser** [comment]
Thanks @jkotin. 

I thought about the wording too, but it needs to work for one year, several years, or no years!

**Comment by clmahoney** [comment]
- YES, when I generated the URL preview for general member browse, I got this: 
![Screen Shot 2020-05-13 at 4 59 36 PM](https://user-images.githubusercontent.com/16673934/81865134-88442d80-953b-11ea-82f8-0902dccd9d51.png)
- YES, when I generated the URL preview for an individual member bio page (Bernice Abbott), I got this: ![Screen Shot 2020-05-13 at 4 59 11 PM](https://user-images.githubusercontent.com/16673934/81865245-a14cde80-953b-11ea-97ac-5cf08ea20311.png)
- YES, when I generated the URL preview for an individual member borrowing activity (Pauline Alderman), I got this: 
![Screen Shot 2020-05-13 at 5 00 44 PM](https://user-images.githubusercontent.com/16673934/81865367-cfcab980-953b-11ea-8dfa-f6715dc4bdf7.png)
- YES, when I generated the URL preview for an individual member membership activity (Pauline Alderman), I got this: 
![Screen Shot 2020-05-13 at 5 00 52 PM](https://user-images.githubusercontent.com/16673934/81865394-de18d580-953b-11ea-975f-30549285811a.png)

- NO, when I generated the URL preview for an individual member's cards list, I don't see a clear image, I see this: 
![Screen Shot 2020-05-13 at 5 01 10 PM](https://user-images.githubusercontent.com/16673934/81865607-1ae4cc80-953c-11ea-9afe-5011989b064f.png)
- But YES, when I generated the URL preview for an individual member's card page (i.e. I clicked on one), I DO see the card image: 
![Screen Shot 2020-05-13 at 5 01 26 PM](https://user-images.githubusercontent.com/16673934/81865709-37810480-953c-11ea-8916-45a3e6b8268f.png)

- YES, when I generated the URL preview for the book browse, I got this: 
![Screen Shot 2020-05-13 at 5 08 07 PM](https://user-images.githubusercontent.com/16673934/81865887-71eaa180-953c-11ea-81fb-a4eb25f8e49d.png)
- YES, when I generated the URL preview for "The 12:30 from Croydon" bio, I saw this: 
![Screen Shot 2020-05-13 at 5 08 21 PM](https://user-images.githubusercontent.com/16673934/81865983-8cbd1600-953c-11ea-9672-8775c37fd634.png)
- YES, when I generated the URL preview for "The 12:30 from Croydon" circulation, I saw this: 
![Screen Shot 2020-05-13 at 5 10 42 PM](https://user-images.githubusercontent.com/16673934/81866190-d86fbf80-953c-11ea-977b-ec6550f94251.png)
- YES, when I generated the URL preview for "The 12:30 from Croydon" card list,  I saw this: 
![Screen Shot 2020-05-13 at 5 10 58 PM](https://user-images.githubusercontent.com/16673934/81866206-defe3700-953c-11ea-95a1-60d1b3f9e397.png)
- NO, when I generated the URL preview for Killen's borrow card for "The 12:30 from Croydon" card list,  I saw this non-image: 
![Screen Shot 2020-05-13 at 5 12 51 PM](https://user-images.githubusercontent.com/16673934/81866367-14a32000-953d-11ea-8dab-70788cb6ae04.png)

**Comment by rlskoeser** [comment]
@clmahoney would you try putting the failing urls into the twitter validator twice ? I had some weird behavior with that, it would fail and then work

**Comment by clmahoney** [comment]
@rlskoeser Yes you're right, that's so weird! If I tried for a second time with Killen's borrow card for "The 12:30 from Croydon" and with Alderman's cards list, I saw the image of the card on the preview! Why is that happening??

**Comment by rlskoeser** [comment]
I think this may be related to the fact that the preview images based on lending cards are IIIF images coming from PUL; perhaps they aren't being generated quickly enough on the first try, but are ready when we hit it again? Based on fact that they're loading correctly the second time, I think I'm generating this correctly in the site code.

The preview images also look ok in an opengraph/twitter preview browser plugin I have installed (it doesn't always exactly reflect how things will look, but gives some idea).

@thatbudakguy do you have any thoughts or concerns about the IIIF preview images? Unless you can think of anything we should change, I think we should close.

**Comment by thatbudakguy** [comment]
agree very weird; but i think your guess is reasonable - perhaps the load time required for the IIIF server to generate a derivative results in a timeout on the first try. OK to close.
